# Generated by Django 5.1.5 on 2025-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(error_messages={'unique': 'A user with that contact already exists.'}, help_text='Required. 15 characters or fewer.', unique=True),
        ),
    ]
