# Generated by Django 5.1.5 on 2025-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.IntegerField(error_messages={'unique': 'A user with that contact already exists.'}, unique=True),
        ),
    ]
