# Generated by Django 5.1.6 on 2025-03-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orders_productid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
