# Generated by Django 5.1.5 on 2025-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
