# Generated by Django 5.1.5 on 2025-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('homework', models.TextField(blank=True)),
                ('assigned_class', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
