# Generated by Django 5.1.6 on 2025-05-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(error_messages={'unique': 'A seller with this email address already exists.'}, max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
