# Generated by Django 5.1.5 on 2025-05-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_price'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_category', to='category.category'),
        ),
    ]
