# Generated by Django 5.1.6 on 2025-05-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_category'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sellerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='sellers.seller'),
        ),
    ]
