# Generated by Django 5.1.6 on 2025-05-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_products_userid_products_sellerid'),
        ('sellers', '0001_initial'),
        ('users', '0002_alter_users_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField(unique=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.products')),
                ('sellerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sellers.seller')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
