# Generated by Django 5.1.5 on 2025-04-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField(error_messages={'unique': 'A user with that contact already exists.'}, max_length=7, unique=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.products')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
