# Generated by Django 5.1.5 on 2025-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('usedtime', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
