# Generated by Django 5.1.5 on 2025-05-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_category_alter_products_price'),
        ('users', '0002_alter_users_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.users'),
        ),
    ]
