# Generated by Django 5.1.6 on 2025-05-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_userid'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='userid',
        ),
        migrations.AddField(
            model_name='products',
            name='sellerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='sellers.seller'),
        ),
    ]
